FROM python:3.12-slim

WORKDIR /app


# Install uv
RUN pip install --no-cache-dir uv


# Copy dependency files
COPY pyproject.toml uv.lock README.md ./


# Install backend dependencies
ENV UV_HTTP_TIMEOUT=300

RUN uv sync --no-dev


# Copy application
COPY app ./app
COPY data ./data


EXPOSE 8000


CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]