FROM python:3.12-slim


WORKDIR /app


RUN pip install --no-cache-dir uv


COPY pyproject.toml uv.lock README.md ./


ENV UV_HTTP_TIMEOUT=300

RUN uv sync --no-dev


COPY frontend ./frontend


EXPOSE 8501


CMD ["uv","run","streamlit","run","frontend/streamlit_app.py","--server.address=0.0.0.0"]