FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UV_HTTP_TIMEOUT=300
ENV HF_HOME=/app/.cache/huggingface

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --no-dev --frozen

# Cache embedding model in the image.
RUN uv run python -c \
    "from sentence_transformers import SentenceTransformer; \
    SentenceTransformer('BAAI/bge-small-en-v1.5')"

ENV HF_HUB_OFFLINE=1
ENV TRANSFORMERS_OFFLINE=1

COPY app ./app

# Alembic migration files
COPY alembic ./alembic
COPY alembic.ini ./alembic.ini

COPY data ./data

EXPOSE 8000

CMD ["sh","-c","uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"]